### ISSUE TITLE
how to write good commit messages

### ISSUE THREAD

**Issue by frangrit** [rumors-studio/knowledgebase#4]
Would be nice in the development section, esp for new devs, or non-devs who occasionally commit, like me.

**Comment by whoisgina** [comment]
A few notes on this: 
- Commit early and often
- Be descriptive
- Reference relevant issues
- Close an issue with a commit

@zackseuberling probably has ideas too.

**Comment by frangrit** [comment]
https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
http://chris.beams.io/posts/git-commit/

If you add more thoughts here, between that and the articles above I could
probably cobble something together myself for the team to review.
